# Test Settings
mode: test
experiment_name: first_run # Experiment name to load

eval_on: test # Evaluation on 'test' or 'val' set
load_path: null 
criterion: L1 # Criterion for evaluation
stat_dir: ./outputs/eval/ # Folder to save evaluation results
checkpoint_path: ./outputs/checkpoints/batvision_unet_batvisionv2_BS32_Lr0.0001_AdamW_batvisionunet_first_full_run # Path to the checkpoint to load
checkpoint_epoch: 200 # Epoch of the checkpoint to load

num_threads: 4
batch_size: 1

use_tensorboard: False # Use Tensorboard to display images and loss
use_wandb: True # Use Weights & Biases to log images and loss
wandb_id: 0ev9zotx # wandb run id to resume
wandb_api_key:  # Your wandb API key